In [14]:
import pandas as pd
import requests

addr = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/"
appkey = "61510a68756f4bff910a68756f6bffeb?"
params = "startDate=20170101&endDate=20170101"

url_addr = addr + appkey + params
url_addr

'https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/61510a68756f4bff910a68756f6bffeb?startDate=20170101&endDate=20170101'

In [13]:
re = requests.get(url_addr).json()
re

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
json_data["totCnt"]

In [ ]:
df = pd.DataFrame(json_data["data"])
df

In [ ]:
df.to_csv("20170101.csv", mode="w", encoding="utf-8-sig")

In [ ]:
df.to_csv("20170101.csv", mode="a", encoding="utf-8-sig", header=False)

In [ ]:
# 포문테스트
for i in range(1,775):
    number = i
    param = params + str(number)
    json_data = requests.get(url,param).json()
    df = pd.DataFrame(json_data["data"])
    df.to_csv("20170101.csv", mode="a", encoding="utf-8-sig", header=False)

In [17]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/61510a68756f4bff910a68756f6bffeb?"
params = "startDate=20170101" + "&endDate=20191231" + "&limit=100&number=1"
re = requests.get(url,params).json()
re["totCnt"]

774

In [69]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/55369c5ad902457ab69c5ad902157a44?"
for i in range(20190701, 20190732):
    for n in range(1, 9):
        params = "startDate="+ str(i) + "&endDate=20170131" + "&limit=100&number=" + str(n)
        json_data = requests.get(url, params).json()
        df = pd.DataFrame(json_data["data"])
        df.to_csv("201907.csv", mode="a", encoding="utf-8-sig", header=False)

In [70]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/55369c5ad902457ab69c5ad902157a44?"
for i in range(20190801, 20190832):
    for n in range(1, 9):
        params = "startDate="+ str(i) + "&endDate=20170131" + "&limit=100&number=" + str(n)
        json_data = requests.get(url, params).json()
        df = pd.DataFrame(json_data["data"])
        df.to_csv("201908.csv", mode="a", encoding="utf-8-sig", header=False)

In [74]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/6297ad810cf2414497ad810cf2214488?"
for i in range(20190901, 20190931):
    for n in range(1, 9):
        params = "startDate="+ str(i) + "&endDate=20170131" + "&limit=100&number=" + str(n)
        json_data = requests.get(url, params).json()
        df = pd.DataFrame(json_data["data"])
        df.to_csv("201909.csv", mode="a", encoding="utf-8-sig", header=False)

In [75]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/6297ad810cf2414497ad810cf2214488?"
for i in range(20191001, 20191032):
    for n in range(1, 9):
        params = "startDate="+ str(i) + "&endDate=20170131" + "&limit=100&number=" + str(n)
        json_data = requests.get(url, params).json()
        df = pd.DataFrame(json_data["data"])
        df.to_csv("201910.csv", mode="a", encoding="utf-8-sig", header=False)

In [76]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/6297ad810cf2414497ad810cf2214488?"
for i in range(20191101, 20191131):
    for n in range(1, 9):
        params = "startDate="+ str(i) + "&endDate=20170131" + "&limit=100&number=" + str(n)
        json_data = requests.get(url, params).json()
        df = pd.DataFrame(json_data["data"])
        df.to_csv("201911.csv", mode="a", encoding="utf-8-sig", header=False)

In [78]:
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/2091358b30e611eabf4805544c722b34/2de9c7217d9b4318a9c7217d9be3189b?"
for i in range(20191201, 20191232):
    for n in range(1, 9):
        params = "startDate="+ str(i) + "&endDate=20170131" + "&limit=100&number=" + str(n)
        json_data = requests.get(url, params).json()
        df = pd.DataFrame(json_data["data"])
        df.to_csv("201912.csv", mode="a", encoding="utf-8-sig", header=False)

In [ ]:
ㅠㅠ

In [326]:
# 갯수확인
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/f397788743c111e994c4ef64bf51b7cf/"
appkey = "ae7d0d76cc704c4ebd0d76cc702c4e96?"
startDate = "20191101"
endDate = "20191131"

urls = url + appkey + "startDate=" + startDate + "&endDate=" + endDate + "&limit=100"
json_data = requests.get(urls).json()

In [327]:
json_data['totCnt']

0

In [323]:
# 뽑기
import pandas as pd
import requests

url = "https://gw.jejudatahub.net/api/proxy/f397788743c111e994c4ef64bf51b7cf/"
appkey = "4a9665f926da47a99665f926dab7a9a9?"
startDate = "20191016"
endDate = "20191031"

# for i in range(20170101, 20170116):
for n in range(1, 149):
    # params = "startDate="+ startDate + "&endDate=" + endDate + "&limit=100&number=" + str(n)
    urls = url + appkey + "startDate=" + startDate + "&endDate=" + endDate + "&limit=100&number=" + str(n)
    json_data = requests.get(urls).json()
    df = pd.DataFrame(json_data["data"])
    df.to_csv("201910b.csv", mode="a", encoding="utf-8-sig", header=False)

In [27]:
import pandas as pd
df2 = pd.read_excel("오등동 201911.xlsx", sheet_name="Sheet1")
df1 = pd.read_excel("오등동 201912.xlsx", sheet_name="Sheet1")

In [28]:
df = pd.concat([df1,df2])

In [29]:
df

      월.일       최대순간풍향  최저기온  최고기온  일강우량  최저습도  최고습도    최저기압    최고기압
0   12.31  337.5 / NNW  -0.8   3.7   0.0    56    79  1029.9  1036.4
1   12.30   315.0 / NW   3.8  12.8   0.0    69    98  1020.5  1030.0
2   12.29  101.3 / ESE   3.8  14.8  14.5    66   100  1019.0  1028.1
3   12.28    33.8 / NE   1.2   7.5   0.0    54    89  1027.1  1030.1
4   12.27   320.6 / NW   3.1   4.5   0.0    55    76  1021.8  1028.1
..    ...          ...   ...   ...   ...   ...   ...     ...     ...
25  11.05      5.6 / N   9.6  18.2   0.0    63    92  1018.1  1020.7
26  11.04    36.6 / NE   9.1  19.6   0.0    59    97  1019.3  1022.0
27  11.03  109.7 / ESE  10.7  18.8   0.0    67    93  1017.9  1021.5
28  11.02  329.1 / NNW  11.2  21.2   0.0    55    99  1017.7  1021.8
29  11.01  165.9 / SSE  10.6  21.4   0.0    37    95  1020.1  1023.8

[61 rows x 9 columns]

In [32]:
df.sort_values("월.일", ascending=True)
df

      월.일       최대순간풍향  최저기온  최고기온  일강우량  최저습도  최고습도    최저기압    최고기압
0   12.31  337.5 / NNW  -0.8   3.7   0.0    56    79  1029.9  1036.4
1   12.30   315.0 / NW   3.8  12.8   0.0    69    98  1020.5  1030.0
2   12.29  101.3 / ESE   3.8  14.8  14.5    66   100  1019.0  1028.1
3   12.28    33.8 / NE   1.2   7.5   0.0    54    89  1027.1  1030.1
4   12.27   320.6 / NW   3.1   4.5   0.0    55    76  1021.8  1028.1
..    ...          ...   ...   ...   ...   ...   ...     ...     ...
25  11.05      5.6 / N   9.6  18.2   0.0    63    92  1018.1  1020.7
26  11.04    36.6 / NE   9.1  19.6   0.0    59    97  1019.3  1022.0
27  11.03  109.7 / ESE  10.7  18.8   0.0    67    93  1017.9  1021.5
28  11.02  329.1 / NNW  11.2  21.2   0.0    55    99  1017.7  1021.8
29  11.01  165.9 / SSE  10.6  21.4   0.0    37    95  1020.1  1023.8

[61 rows x 9 columns]

In [2]:
import pandas as pd
df = pd.read_excel("한림읍 명월리 201701.xlsx", sheet_name="Sheet1")
df

     월.일       최대순간풍향  최저기온  최고기온  일강우량  최저습도  최고습도   최저기압   최고기압
0   1.01    37.6 / NE   4.3  12.3   0.0    60    82  ( : )  ( : )
1   1.02   22.0 / NNE   8.5  13.8   0.5    74    94  ( : )  ( : )
2   1.03    35.9 / NE   4.3  10.7   0.0    58    86  ( : )  ( : )
3   1.04   27.5 / NNE   4.2  12.2   0.0    52    85  ( : )  ( : )
4   1.05     83.8 / E   7.9  14.1   0.0    62    84  ( : )  ( : )
5   1.06     99.1 / E   7.1  14.7   0.5    55    87  ( : )  ( : )
6   1.07   68.4 / ENE   5.4  13.8   7.5    72    98  ( : )  ( : )
7   1.08    55.3 / NE   9.1  12.8   6.0    69    99  ( : )  ( : )
8   1.09      5.4 / N   5.6   9.3   0.0    61    81  ( : )  ( : )
9   1.10    352.4 / N   4.9   7.1   0.0    50    69  ( : )  ( : )
10  1.11    359.7 / N   3.2   5.0   0.0    54    68  ( : )  ( : )
11  1.12   308.8 / NW   4.7   9.7   0.0    46    80  ( : )  ( : )
12  1.13    273.4 / W   3.0   9.7   0.0    44    66  ( : )  ( : )
13  1.14   18.8 / NNE   1.3   4.1   0.0    49    68  ( : )  ( : )
14  1.15   15.6 / NNE   0.6   4.4   0.0    48    66  ( : )  ( : )
15  1.16      3.3 / N   1.4   5.4   0.0    50    69  ( : )  ( : )
16  1.17   24.9 / NNE   0.9   7.3   0.0    59    79  ( : )  ( : )
17  1.18    36.3 / NE   2.3   7.5   0.0    56    83  ( : )  ( : )
18  1.19    33.8 / NE   4.1   7.5   0.0    57    72  ( : )  ( : )
19  1.20      8.2 / N   0.2   7.3   1.0    49    86  ( : )  ( : )
20  1.21   17.7 / NNE   2.0   6.3   0.0    52    73  ( : )  ( : )
21  1.22    351.3 / N   1.1   6.1   1.5    46    88  ( : )  ( : )
22  1.23   33.1 / NNE   0.4   3.6   0.0    49    77  ( : )  ( : )
23  1.24    353.1 / N   1.9   4.7   0.0    52    77  ( : )  ( : )
24  1.25   24.9 / NNE   0.3   5.9   0.0    55    72  ( : )  ( : )
25  1.26    40.1 / NE   0.4   8.8   0.0    55    78  ( : )  ( : )
26  1.27   304.5 / NW   0.8  10.9   0.0    51    87  ( : )  ( : )
27  1.28  203.7 / SSW   0.7  13.0   0.0    42    76  ( : )  ( : )
28  1.29      4.5 / N   7.7  17.5   3.0    51    97  ( : )  ( : )
29  1.30  211.0 / SSW   1.2   8.0   0.0    58    96  ( : )  ( : )
30  1.31   25.3 / NNE   0.2   5.0   0.0    59    73  ( : )  ( : )

In [35]:
import pandas as pd
import os

os.chdir("D:/weather/강정동")

df1 = pd.read_excel("강정동 201701.xlsx", sheet_name="강정동 201701.csv")
df2 = pd.read_excel("강정동 201703.xlsx", sheet_name="강정동 201703.csv")
# df3 = pd.read_excel("강정동 201703.xlsx", sheet_name="강정동 201703.csv")
# df4 = pd.read_excel("강정동 201704.xlsx", sheet_name="강정동 201704.csv")
# df5 = pd.read_excel("강정동 201705.xlsx", sheet_name="강정동 201705.csv")
# df6 = pd.read_excel("강정동 201706.xlsx", sheet_name="강정동 201706.csv")
# df7 = pd.read_excel("강정동 201707.xlsx", sheet_name="강정동 201707.csv")
# df8 = pd.read_excel("강정동 201708.xlsx", sheet_name="강정동 201708.csv")
# df9 = pd.read_excel("강정동 201709.xlsx", sheet_name="강정동 201709.csv")
# df10 = pd.read_excel("강정동 201710.xlsx", sheet_name="강정동 201710.csv")
# df11 = pd.read_excel("강정동 201711.xlsx", sheet_name="강정동 201711.csv")
# df12 = pd.read_excel("강정동 201712.xlsx", sheet_name="강정동 201712.csv")

dd = pd.concat([df1,df2])
#,df4,df5,df6,df7,df8,df9,df10,df11,df12

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [36]:
dd

,월.일,일강우량,최고기압,최고기온,최고습도,최대순간풍향,최저기압,최저기온,최저습도,3.01,309.4 / NW,4.7,15,0,46,85
0,1.01,0.0,NaN,14.4,92.0,163.1 / SSE,NaN,3.0,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.02,0.0,NaN,15.0,97.0,115.3 / ESE,NaN,7.8,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.03,0.0,NaN,15.7,94.0,135.0 / SE,NaN,5.9,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.04,0.0,NaN,15.7,85.0,112.5 / ESE,NaN,3.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.05,0.0,NaN,14.3,90.0,95.6 / E,NaN,7.5,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.27,348.8 / N,5.2,12.2,2.5,36.0,91.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.28,210.9 / SSW,2.5,14.7,0.0,33.0,80.0
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.29,210.9 / SSW,8.3,17.0,5.0,74.0,96.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.30,185.6 / S,7.2,16.7,0.0,59.0,93.0
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.31,250.3 / WSW,6.6,14.3,7.5,61.0,95.0

In [9]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/오등동")

df1 = pd.read_excel("오등동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("오등동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("오등동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("오등동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("오등동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("오등동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("오등동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("오등동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("오등동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("오등동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("오등동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("오등동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [10]:
data.to_csv('오등동 2017.csv',header = True, index = True, encoding = 'UTF-8')

In [15]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/오등동")

df1 = pd.read_excel("오등동 201801.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("오등동 201802.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("오등동 201803.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("오등동 201804.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("오등동 201805.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("오등동 201806.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("오등동 201807.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("오등동 201808.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("오등동 201809.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("오등동 201810.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("오등동 201811.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("오등동 201812.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [16]:
data.to_csv('오등동 2018.csv',header = True, index = True, encoding = 'UTF-8')

In [17]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/오등동")

df1 = pd.read_excel("오등동 201901.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("오등동 201902.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("오등동 201903.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("오등동 201904.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("오등동 201905.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("오등동 201906.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("오등동 201907.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("오등동 201908.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("오등동 201909.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("오등동 201910.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("오등동 201911.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("오등동 201912.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [18]:
data.to_csv('오등동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [23]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/용담이동")

df1 = pd.read_excel("용담이동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("용담이동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("용담이동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("용담이동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("용담이동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("용담이동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("용담이동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("용담이동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("용담이동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("용담이동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("용담이동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("용담이동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [24]:
data.to_csv('용담 2017.csv',header = True, index = True, encoding = 'UTF-8')

In [25]:
data

      월.일      최대순간풍향  최저기온  최고기온  일강우량 최저습도 최고습도    최저기압    최고기압
0    1.01    80.0 / E   5.0  11.8   0.0   50   69  1024.9  1031.2
1    1.02   180.0 / S   9.3  13.3   0.5   64   85  1022.0  1025.0
2    1.03  320.0 / NW   5.0  10.9   0.0   45   80  1024.0  1026.9
3    1.04  60.0 / ENE   4.1  11.2   0.0   41   74  1022.7  1025.8
4    1.05   100.0 / E   7.8  13.4   5.0   60   85  1022.4  1024.6
..    ...         ...   ...   ...   ...  ...  ...     ...     ...
26  12.27  30.0 / NNE   2.1   4.7   0.0   44   58  1029.2  1032.1
27  12.28  60.0 / ENE   1.6   6.8   0.0   46   59  1027.2  1031.6
28  12.29    10.0 / N   3.4  11.1   0.0   47   69  1027.1  1029.8
29  12.30  320.0 / NW   9.1  11.6   1.0   48   81  1022.5  1028.0
30  12.31   350.0 / N   6.4   9.6   1.5   39   81  1022.5  1026.4

[365 rows x 9 columns]

In [28]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/용담이동")

df1 = pd.read_excel("용담이동 201801.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("용담이동 201802.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("용담이동 201803.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("용담이동 201804.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("용담이동 201805.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("용담이동 201806.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("용담이동 201807.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("용담이동 201808.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("용담이동 201809.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("용담이동 201810.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("용담이동 201811.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("용담이동 201812.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [29]:
data.to_csv('용담 2018.csv',header = True, index = True, encoding = 'UTF-8')

In [30]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/용담이동")

df1 = pd.read_excel("용담이동 201901.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("용담이동 201902.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("용담이동 201903.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("용담이동 201904.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("용담이동 201905.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("용담이동 201906.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("용담이동 201907.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("용담이동 201908.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("용담이동 201909.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("용담이동 201910.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("용담이동 201911.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("용담이동 201912.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [31]:
data.to_csv('용담 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [32]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/우도")

df1 = pd.read_excel("우도 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("우도 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("우도 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("우도 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("우도 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("우도 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("우도 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("우도 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("우도 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("우도 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("우도 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("우도 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [33]:
data.to_csv('우도 2017.csv',header = True, index = True, encoding = 'UTF-8')

In [34]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/우도")

df1 = pd.read_excel("우도 201801.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("우도 201802.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("우도 201803.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("우도 201804.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("우도 201805.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("우도 201806.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("우도 201807.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("우도 201808.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("우도 201809.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("우도 201810.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("우도 201811.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("우도 201812.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [35]:
data.to_csv('우도 2018.csv',header = True, index = True, encoding = 'UTF-8')

In [36]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/우도")

df1 = pd.read_excel("우도 201901.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("우도 201902.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("우도 201903.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("우도 201904.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("우도 201905.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("우도 201906.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("우도 201907.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("우도 201908.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("우도 201909.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("우도 201910.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("우도 201911.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("우도 201912.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

In [37]:
data.to_csv('우도 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [40]:
data.to_csv('원정 2017.csv',header = True, index = True, encoding = 'UTF-8')

In [42]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/월정리")

df1 = pd.read_excel("월정 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("월정 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("월정 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("월정 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("월정 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("월정 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("월정 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("월정 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("월정 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("월정 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("월정 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("월정 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("월정 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("월정 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("월정 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("월정 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("월정 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("월정 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("월정 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("월정 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("월정 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("월정 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("월정 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("월정 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("월정 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("월정 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("월정 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("월정 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("월정 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("월정 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("월정 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("월정 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("월정 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("월정 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("월정 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("월정 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [43]:
data.to_csv('월정 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('월정 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('월정 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [44]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/중문 색달동")

df1 = pd.read_excel("색달동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("색달동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("색달동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("색달동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("색달동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("색달동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("색달동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("색달동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("색달동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("색달동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("색달동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("색달동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("색달동 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("색달동 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("색달동 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("색달동 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("색달동 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("색달동 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("색달동 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("색달동 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("색달동 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("색달동 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("색달동 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("색달동 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("색달동 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("색달동 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("색달동 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("색달동 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("색달동 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("색달동 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("색달동 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("색달동 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("색달동 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("색달동 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("색달동 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("색달동 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [45]:
data.to_csv('색달동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('색달동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('색달동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [46]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/표선")

df1 = pd.read_excel("표선읍 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("표선읍 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("표선읍 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("표선읍 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("표선읍 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("표선읍 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("표선읍 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("표선읍 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("표선읍 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("표선읍 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("표선읍 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("표선읍 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("표선읍 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("표선읍 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("표선읍 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("표선읍 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("표선읍 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("표선읍 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("표선읍 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("표선읍 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("표선읍 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("표선읍 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("표선읍 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("표선읍 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("표선읍 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("표선읍 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("표선읍 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("표선읍 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("표선읍 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("표선읍 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("표선읍 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("표선읍 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("표선읍 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("표선읍 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("표선읍 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("표선읍 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [47]:
data.to_csv('표선읍 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('표선읍 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('표선읍 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [48]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/한림읍")

df1 = pd.read_excel("한림읍 명월리 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("한림읍 명월리 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("한림읍 명월리 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("한림읍 명월리 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("한림읍 명월리 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("한림읍 명월리 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("한림읍 명월리 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("한림읍 명월리 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("한림읍 명월리 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("한림읍 명월리 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("한림읍 명월리 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("한림읍 명월리 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("한림읍 명월리 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("한림읍 명월리 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("한림읍 명월리 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("한림읍 명월리 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("한림읍 명월리 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("한림읍 명월리 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("한림읍 명월리 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("한림읍 명월리 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("한림읍 명월리 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("한림읍 명월리 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("한림읍 명월리 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("한림읍 명월리 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("한림읍 명월리 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("한림읍 명월리 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("한림읍 명월리 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("한림읍 명월리 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("한림읍 명월리 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("한림읍 명월리 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("한림읍 명월리 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("한림읍 명월리 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("한림읍 명월리 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("한림읍 명월리 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("한림읍 명월리 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("한림읍 명월리 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [49]:
data.to_csv('한림읍 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('한림읍 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('한림읍 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [50]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/아라동")

df1 = pd.read_excel("아라동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("아라동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("아라동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("아라동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("아라동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("아라동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("아라동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("아라동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("아라동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("아라동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("아라동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("아라동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("아라동 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("아라동 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("아라동 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("아라동 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("아라동 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("아라동 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("아라동 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("아라동 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("아라동 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("아라동 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("아라동 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("아라동 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("아라동 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("아라동 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("아라동 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("아라동 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("아라동 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("아라동 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("아라동 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("아라동 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("아라동 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("아라동 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("아라동 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("아라동 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [51]:
data.to_csv('아라동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('아라동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('아라동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [52]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/성산 2차가공")

df1 = pd.read_excel("성산 201701.csv.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("성산 201702.csv.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("성산 201703.csv.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("성산 201704.csv.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("성산 201705.csv.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("성산 201706.csv.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("성산 201707.csv.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("성산 201708.csv.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("성산 201709.csv.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("성산 201710.csv.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("성산 201711.csv.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("성산 201712.csv.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("성산 201801.csv.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("성산 201802.csv.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("성산 201803.csv.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("성산 201804.csv.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("성산 201805.csv.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("성산 201806.csv.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("성산 201807.csv.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("성산 201808.csv.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("성산 201809.csv.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("성산 201810.csv.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("성산 201811.csv.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("성산 201812.csv.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("성산 201901.csv.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("성산 201902.csv.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("성산 201903.csv.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("성산 201904.csv.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("성산 201905.csv.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("성산 201906.csv.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("성산 201907.csv.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("성산 201908.csv.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("성산 201909.csv.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("성산 201910.csv.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("성산 201911.csv.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("성산 201912.csv.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

XLRDError: No sheet named <'Sheet1'>

In [53]:
data.to_csv('성산 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('성산 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('성산 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [54]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/서호동 2차가공")

df1 = pd.read_excel("서호동 201701.csv.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("서호동 201702.csv.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("서호동 201703.csv.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("서호동 201704.csv.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("서호동 201705.csv.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("서호동 201706.csv.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("서호동 201707.csv.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("서호동 201708.csv.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("서호동 201709.csv.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("서호동 201710.csv.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("서호동 201711.csv.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("서호동 201712.csv.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("서호동 201801.csv.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("서호동 201802.csv.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("서호동 201803.csv.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("서호동 201804.csv.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("서호동 201805.csv.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("서호동 201806.csv.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("서호동 201807.csv.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("서호동 201808.csv.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("서호동 201809.csv.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("서호동 201810.csv.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("서호동 201811.csv.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("서호동 201812.csv.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("서호동 201901.csv.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("서호동 201902.csv.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("서호동 201903.csv.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("서호동 201904.csv.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("서호동 201905.csv.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("서호동 201906.csv.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("서호동 201907.csv.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("서호동 201908.csv.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("서호동 201909.csv.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("서호동 201910.csv.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("서호동 201911.csv.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("서호동 201912.csv.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

XLRDError: No sheet named <'Sheet1'>

In [55]:
data.to_csv('서호동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('서호동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('서호동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [56]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/서귀포 서귀동 2차가공")

df1 = pd.read_excel("서귀동 201701.csv.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("서귀동 201702.csv.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("서귀동 201703.csv.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("서귀동 201704.csv.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("서귀동 201705.csv.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("서귀동 201706.csv.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("서귀동 201707.csv.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("서귀동 201708.csv.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("서귀동 201709.csv.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("서귀동 201710.csv.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("서귀동 201711.csv.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("서귀동 201712.csv.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("서귀동 201801.csv.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("서귀동 201802.csv.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("서귀동 201803.csv.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("서귀동 201804.csv.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("서귀동 201805.csv.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("서귀동 201806.csv.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("서귀동 201807.csv.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("서귀동 201808.csv.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("서귀동 201809.csv.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("서귀동 201810.csv.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("서귀동 201811.csv.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("서귀동 201812.csv.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("서귀동 201901.csv.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("서귀동 201902.csv.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("서귀동 201903.csv.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("서귀동 201904.csv.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("서귀동 201905.csv.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("서귀동 201906.csv.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("서귀동 201907.csv.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("서귀동 201908.csv.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("서귀동 201909.csv.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("서귀동 201910.csv.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("서귀동 201911.csv.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("서귀동 201912.csv.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

XLRDError: No sheet named <'Sheet1'>

In [57]:
data.to_csv('서귀동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('서귀동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('서귀동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [58]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/대정읍")

df1 = pd.read_excel("대정읍 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("대정읍 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("대정읍 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("대정읍 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("대정읍 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("대정읍 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("대정읍 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("대정읍 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("대정읍 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("대정읍 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("대정읍 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("대정읍 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("대정읍 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("대정읍 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("대정읍 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("대정읍 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("대정읍 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("대정읍 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("대정읍 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("대정읍 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("대정읍 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("대정읍 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("대정읍 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("대정읍 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("대정읍 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("대정읍 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("대정읍 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("대정읍 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("대정읍 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("대정읍 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("대정읍 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("대정읍 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("대정읍 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("대정읍 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("대정읍 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("대정읍 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [59]:
data.to_csv('대정읍 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('대정읍 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('대정읍 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [60]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/남원읍")

df1 = pd.read_excel("남원읍 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("남원읍 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("남원읍 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("남원읍 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("남원읍 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("남원읍 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("남원읍 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("남원읍 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("남원읍 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("남원읍 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("남원읍 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("남원읍 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("남원읍 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("남원읍 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("남원읍 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("남원읍 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("남원읍 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("남원읍 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("남원읍 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("남원읍 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("남원읍 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("남원읍 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("남원읍 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("남원읍 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("남원읍 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("남원읍 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("남원읍 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("남원읍 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("남원읍 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("남원읍 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("남원읍 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("남원읍 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("남원읍 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("남원읍 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("남원읍 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("남원읍 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [61]:
data.to_csv('남원읍 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('남원읍 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('남원읍 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [62]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/구좌")

df1 = pd.read_excel("구좌 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("구좌 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("구좌 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("구좌 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("구좌 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("구좌 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("구좌 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("구좌 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("구좌 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("구좌 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("구좌 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("구좌 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("구좌 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("구좌 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("구좌 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("구좌 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("구좌 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("구좌 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("구좌 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("구좌 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("구좌 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("구좌 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("구좌 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("구좌 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("구좌 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("구좌 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("구좌 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("구좌 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("구좌 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("구좌 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("구좌 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("구좌 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("구좌 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("구좌 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("구좌 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("구좌 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [63]:
data.to_csv('구좌 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('구좌 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('구좌 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [64]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/건입동")

df1 = pd.read_excel("건입동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("건입동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("건입동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("건입동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("건입동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("건입동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("건입동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("건입동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("건입동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("건입동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("건입동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("건입동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("건입동 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("건입동 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("건입동 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("건입동 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("건입동 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("건입동 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("건입동 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("건입동 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("건입동 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("건입동 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("건입동 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("건입동 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("건입동 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("건입동 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("건입동 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("건입동 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("건입동 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("건입동 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("건입동 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("건입동 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("건입동 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("건입동 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("건입동 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("건입동 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

In [65]:
data.to_csv('건입동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('건입동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('건입동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [66]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/강정동")

df1 = pd.read_excel("강정동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("강정동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("강정동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("강정동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("강정동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("강정동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("강정동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("강정동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("강정동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("강정동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("강정동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("강정동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("강정동 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("강정동 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("강정동 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("강정동 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("강정동 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("강정동 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("강정동 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("강정동 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("강정동 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("강정동 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("강정동 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("강정동 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("강정동 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("강정동 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("강정동 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("강정동 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("강정동 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("강정동 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("강정동 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("강정동 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("강정동 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("강정동 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("강정동 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("강정동 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

FileNotFoundError: [Errno 2] No such file or directory: '강정동 201801.xlsx'

In [67]:
data.to_csv('강정동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('강정동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('강정동 2019.csv',header = True, index = True, encoding = 'UTF-8')

In [68]:
import pandas as pd
import os

os.chdir("C:/Users/qlswl/Desktop/2차가공완료(날씨)-20200120T145401Z-001/2차가공완료(날씨)/외도")

df1 = pd.read_excel("외도일동 201701.xlsx", sheet_name="Sheet1")
df2 = pd.read_excel("외도일동 201702.xlsx", sheet_name="Sheet1")
df3 = pd.read_excel("외도일동 201703.xlsx", sheet_name="Sheet1")
df4 = pd.read_excel("외도일동 201704.xlsx", sheet_name="Sheet1")
df5 = pd.read_excel("외도일동 201705.xlsx", sheet_name="Sheet1")
df6 = pd.read_excel("외도일동 201706.xlsx", sheet_name="Sheet1")
df7 = pd.read_excel("외도일동 201707.xlsx", sheet_name="Sheet1")
df8 = pd.read_excel("외도일동 201708.xlsx", sheet_name="Sheet1")
df9 = pd.read_excel("외도일동 201709.xlsx", sheet_name="Sheet1")
df10 = pd.read_excel("외도일동 201710.xlsx", sheet_name="Sheet1")
df11 = pd.read_excel("외도일동 201711.xlsx", sheet_name="Sheet1")
df12 = pd.read_excel("외도일동 201712.xlsx", sheet_name="Sheet1")

data = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])


dff1 = pd.read_excel("외도일동 201801.xlsx", sheet_name="Sheet1")
dff2 = pd.read_excel("외도일동 201802.xlsx", sheet_name="Sheet1")
dff3 = pd.read_excel("외도일동 201803.xlsx", sheet_name="Sheet1")
dff4 = pd.read_excel("외도일동 201804.xlsx", sheet_name="Sheet1")
dff5 = pd.read_excel("외도일동 201805.xlsx", sheet_name="Sheet1")
dff6 = pd.read_excel("외도일동 201806.xlsx", sheet_name="Sheet1")
dff7 = pd.read_excel("외도일동 201807.xlsx", sheet_name="Sheet1")
dff8 = pd.read_excel("외도일동 201808.xlsx", sheet_name="Sheet1")
dff9 = pd.read_excel("외도일동 201809.xlsx", sheet_name="Sheet1")
dff10 = pd.read_excel("외도일동 201810.xlsx", sheet_name="Sheet1")
dff11 = pd.read_excel("외도일동 201811.xlsx", sheet_name="Sheet1")
dff12 = pd.read_excel("외도일동 201812.xlsx", sheet_name="Sheet1")

data2 = pd.concat([dff1,dff2,dff3,dff4,dff5,dff6,dff7,dff8,dff9,dff10,dff11,dff12])


dfff1 = pd.read_excel("외도일동 201901.xlsx", sheet_name="Sheet1")
dfff2 = pd.read_excel("외도일동 201902.xlsx", sheet_name="Sheet1")
dfff3 = pd.read_excel("외도일동 201903.xlsx", sheet_name="Sheet1")
dfff4 = pd.read_excel("외도일동 201904.xlsx", sheet_name="Sheet1")
dfff5 = pd.read_excel("외도일동 201905.xlsx", sheet_name="Sheet1")
dfff6 = pd.read_excel("외도일동 201906.xlsx", sheet_name="Sheet1")
dfff7 = pd.read_excel("외도일동 201907.xlsx", sheet_name="Sheet1")
dfff8 = pd.read_excel("외도일동 201908.xlsx", sheet_name="Sheet1")
dfff9 = pd.read_excel("외도일동 201909.xlsx", sheet_name="Sheet1")
dfff10 = pd.read_excel("외도일동 201910.xlsx", sheet_name="Sheet1")
dfff11 = pd.read_excel("외도일동 201911.xlsx", sheet_name="Sheet1")
dfff12 = pd.read_excel("외도일동 201912.xlsx", sheet_name="Sheet1")

data3 = pd.concat([dfff1,dfff2,dfff3,dfff4,dfff5,dfff6,dfff7,dfff8,dfff9,dfff10,dfff11,dfff12])

XLRDError: No sheet named <'Sheet1'>

In [69]:
data.to_csv('외도일동 2017.csv',header = True, index = True, encoding = 'UTF-8')
data2.to_csv('외도일동 2018.csv',header = True, index = True, encoding = 'UTF-8')
data3.to_csv('외도일동 2019.csv',header = True, index = True, encoding = 'UTF-8')